#!/bin/bash

clientsDir="/sv/clients"
client=""
cmd=""

#WARNING for testing make sure you are using dummy commands.
#command for bashrc bindkey -s '^e' 'dashboard.sh^M'

while getopts c: flag
do
	case "${flag}" in
		c) client=${OPTARG};;
	esac
done

function main(){
	if [[ ! -z "$client" ]]; then
		setCommand
		$cmd
		cd "$clientsDir/$client"
		$SHELL
	elif [[ "$(pwd)" =~ /sv/clients/ ]]; then
		client="$(pwd | sed 's|/sv/clients/||' | awk -F/ '{print $1}')"
		setCommand
		echo "Running commands for $client..."
		$cmd
	else
		echo "You have been moved to the selected client..."
		client=$(ls "$clientsDir" | fzf )
		setCommand
		$cmd
		cd "$clientsDir/$client"
		$SHELL
	fi
  exit 0
}

function setCommand(){
	# search for all the commands available in this file
	# except the one on the following this line
	search="$(awk -F: '/run/{print $2}' "$0"| grep -v "/run/" | fzf --prompt="Run command on $client: ")"
	# based on the selection, grab the actual function located on the next line
	cmd="$(awk -v s="$search" '$0~s {getline; print $2}' "$0" | cut -d\( -f1 )"
}

# Commands to run start

# run:Git Stage
function git_stage() {
	echo "Staging files... $client"
}

# run:Git Reset
function git_reset() {
	echo "Reseting files...$client"
}

# run:Downsync Live
function downsync_live(){
	echo "Downsyncing $client database..."
	# sudo sv copyClientDatabase $client live local
}

# run:Downsync Staging
function downsync_staging(){
	echo "Downsyncing $client database..."
	# sudo sv copyClientDatabase $client staging local
}

# run:Backup Staging
function backup_staging() {
	echo "Backing up $client database..."
	# sudo sv backupDb staging_cluster1 client_$client
}

# run:Commit
function commit() {
	echo "Starting SVN commit...$client"
}

# run:Deploy Live
function deploy_live() {
	read -p "Are you sure you want to deploy $client to live? " -n 1 -r
	echo # new line
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		echo "deploying $client to live"
	fi
}

# run:Deploy Staging
function deploy_staging() {
	read -p "Are you sure you want to deploy $client to staging env? " -n 1 -r
	echo # new line
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		echo "deploying $client to staging"
		# sudo sv deployClient $client staging
	fi
}

# run:Test Command
function test(){
	echo "This is a test command...$client"
}

main
